### ISSUE TITLE
get config profile fails with a stack trace

### ISSUE THREAD

**Issue by glitchcrab** [dell/dellemc-openmanage-ansible-modules#28]
I'm using the 1.1 branch with ansible 2.7.1. Running the following:

```yaml
tasks:
- name: get config profile
  dellemc_export_server_config_profile:
    idrac_ip: "{{ ip }}"
    idrac_user: "{{ user }}"
    idrac_pwd: "{{ password }}"
    export_format: 'JSON'
    job_wait: 'True'
    share_name: "{{ output_dir }}"
    scp_components: 'IDRAC'
```
Results in this:

```
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_dellemc_export_server_config_profile_payload_xSwZ3B/__main__.py", line 223, in <module>
  File "/tmp/ansible_dellemc_export_server_config_profile_payload_xSwZ3B/__main__.py", line 209, in main
  File "/tmp/ansible_dellemc_export_server_config_profile_payload_xSwZ3B/ansible_dellemc_export_server_config_profile_payload.zip/ansible/module_utils/dellemc_idrac.py", line 72, in connect
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkinfra.py", line 144, in get_driver
    return self._create_driver(mod, ipaddr, creds, protopref, pOptions)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkinfra.py", line 165, in _create_driver
    drv = self.disc_modules[mod].is_entitytype(self, ipaddr, creds, protopref, mod, pOptions)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkbase.py", line 147, in is_entitytype
    if entity.connect():
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkbase.py", line 251, in connect
    return self.my_connect(pOptions)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkbase.py", line 258, in my_connect
    retval = self.cfactory.identify(self.entityjson)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkconnfactory.py", line 100, in identify
    self.enumerate_list(ejson, *self.pfactory.classifier)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkconnfactory.py", line 191, in enumerate_list
    comp_details = self.enumerate_view(comp)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkconnfactory.py", line 126, in enumerate_view
    retval = connection.enumerate_view(index, True)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkproto.py", line 408, in enumerate_view
    return self._enumerate_view(index, self.views, bTrue)
  File "/usr/local/lib/python2.7/dist-packages/omsdk/sdkproto.py", line 433, in _enumerate_view
    (valid, flist) = chk_func(retval['Data'][clsName], clsName)
TypeError: satisfyme() takes exactly 1 argument (2 given)
```

**Comment by anupamaloke** [comment]
@glitchcrab , I am assuming that it might be an issue with the Ansible python interpreter. If you are running it in a virtualenv, then you might need to set the ansible_python_interpreter correctly.

**Comment by glitchcrab** [comment]
i'm going to close this as i'm no longer working somewhere where i have access to any DRACs.
