### ISSUE TITLE
dellemc.openmanage.ome_application_certificate - "padding error"

### ISSUE THREAD

**Issue by t-readyroc** [dell/dellemc-openmanage-ansible-modules#370]
I'm using the below code to generate the CSR:

~~~yaml
---
- name: Generate the CSR
  hosts: ipamaster
  remote_user: "{{ adminUser }}"
  tasks:
    - name: Generate OpenManage certificate signing request
      dellemc.openmanage.ome_application_certificate:
        hostname: "{{ openManageHost }}"
        username: "{{ openManageUser }}"
        password: "{{ openManagePassword }}"
        validate_certs: no
        command: "generate_csr"
        distinguished_name: "{{ openManageHost }}"
        department_name: "Data Center Operations"
        business_name: "MyCompany"
        locality: "OurTown"
        country_state: "OurState"
        country: "US"
        email: "{{ rootemail }}"
      register: certRequest

    - debug:
        var: certRequest

    - name: Set CSR var
      ansible.builtin.set_fact:
        openManageCSR: "{{ certRequest.csr_status.CertificateData }}"

    - name: Create CSR file
      ansible.builtin.template:
        src: openmanage.{{ mgmt_domain }}.j2
        dest: /tmp/{{ openManageCert.principal_name }}.csr
        owner: "{{ adminUser }}"
        group: "{{ adminUser }}"
        mode: '0666'
~~~

The template only has one line, & has the variable in it:

~~~
ansible-idrac> cat templates/openmanage.mgmt.com.j2 
{{ openManageCSR }}
~~~

The resulting file looks like:

~~~
[root@gr-ipaprd01 ~]# cat /tmp/openmanage.mgmt.com.csr 
-----BEGIN CERTIFICATE REQUEST-----MIIFMDCCAxgCAQAwgbAxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhWaXJnaW5pYTESMBAGA1UEBwwJQXJsaW5ndG9uMRIwEAYDVQQKDAlCbHV2ZWN0b3IxHzAdBgNVBAsMFkRhdGEgQ2VudGVyIE9wZXJhdGlvbnMxJTAjBgNVBAMMHG9wZW5tYW5hZ2UubWdtdC5ibHV2ZWN0b3IuaW8xHjAcBgkqhkiG9w0BCQEWD2l0QGJsdXZlY3Rvci5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOWI3XaaWzz3Rb9uDTWobqmk2/IBWybQAzBGz/mIHFLdhwPYsr1L5RlI3ac2p0bdJ4W31lNmLWiHUJAPGyGx84IlHFADMA8inDZL8tjeXs7vhI04Opai6ZUthL8uImFcc9PvAu52SNglUMYdHVhZDJ7ckKItZNCsktBrIo43BkqBSEmFP1kD84WiXIzRSPg+GCamKBSP/ls2rJMM8UL1cyW9o+JTAjLbOx3kTu5qOnv3mQ6vXWWWLxBbHzv/oDMPSuEgMRk9LVCFJ5E+CPAXX4MYX3xeO2a0W9FSWRTeLBZq2C4pjhgEWkqd/il8vtJGtyGRO0yg6XU6rWbEEgkUXD3L1qPZhOJepB4BF1uh1sEUsS2eEEnc8ZLYrTKab+C2WNJ7mbmzrA2AXGqpFUdyojKl8WHJ23j4K4Gth+RVOlEgKxV9YfCbZog7VDWaxonyj540OFRubx8DNhMHWqhUezije+HbW+GmvZKl/POMLABbAkSTd4V9Ue3dg0+AZH549klvOaw1+Mp4JWxVtHo1uw1GgmewpdRAYH+Qq8xu6FXxTUTm/iCZ85AyPv2MyPjg6xFimN75vF7GdQwCu+77eGcZc664l52gDwO+XK/X0HxxBZ3ExStykirEOzWOSYoBdi8pLJva2+s8k1uLxm0PP6yxJ5kUQCjOPTVd3K2hZpjjAgMBAAGgOjA4BgkqhkiG9w0BCQ4xKzApMCcGA1UdEQQgMB6CHG9wZW5tYW5hZ2UubWdtdC5ibHV2ZWN0b3IuaW8wDQYJKoZIhvcNAQELBQADggIBAIE4K1fTMgBW3NRz5jsbai34F3QCvBOfZqcf+TzYq1FhljN+y5/XPd6WtsaJ0iOzdVRB2ywD2emHByEV7sTa6AowLLNW5ZNyzAJ/r+zJRt+jhpH5Tnpu6DnFn2vJmzpA+NVud4oiN+zzFpAmDHnYs0vVKrw2CgH1WhQvV5YVNyznkUEehIfmu8EvZd3W2klQBqXplbZeCk4nfXHayrfcZt1FhQLb0ElMg4CkBUVnt3/5Ev8M8jLE5zt6QQv0KO1if5fbt0K0jZY07vw6GaABLIf1zGNUu53YV1n3yUk+q36XAVaGKx5Puk2vmisI5RaSucclH4iEVx2FkhRKgD5xbWOZ4cyXFxi+RFp8bgA03d7hmSvn+Q1rYrb4mhHCSpF6NJCrYep2gnieTPfIvcQIqFfeMdBJTLxwgI6kYEZgvaZdB1re48CBPQ1WZ+HI2Mz0i0HX3hljGLnOL4PO5RuU+UNH+PGp9O51R1eVnEdX7CDcjJbdYYR4MmCi26hexxPZCPjmJUct056gc5yfplFGCX7/Vx6nrXfyF5HHoUZL3Oc5YkyR4FM4Or4ATaJGy7zO+tZvrPX68BlDWapPZK/u85N0nBd5G9I5FSGTE4DsharSHGPmeU3ML6jqYWrAQXyKFP8ERE02ndQwg9Uf4LTU3IL92/DCTpg57kYn8pZfsa3o-----END CERTIFICATE REQUEST-----
~~~

I then pass this file to IPA like so:

~~~yaml
- name: Pass the CSR to IPA
  command:
    cmd: >
      ipa cert-request /tmp/{{ openManageCert.principal_name }}.csr
      --principal={{ openManageCert.service_type }}/{{ openManageCert.principal_name }} --add
      --certificate-out /tmp/{{ openManageCert.ssl_cert_name }}
  register: cert_request
  failed_when:
    - cert_request.stderr is defined
    - "'ERROR' in cert_request.stderr"
~~~

The playbook results in the following output:

~~~yaml
TASK [Pass the CSR to IPA] **********************************************************************************************************************************************************************************************************************
fatal: [gr-ipaprd01.mgmt.com]: FAILED! => changed=true 
  cmd:
  - ipa
  - cert-request
  - /tmp/openmanage.mgmt.com.csr
  - --principal=HTTP/openmanage.mgmt.com
  - --add
  - --certificate-out
  - /tmp/openmanage.mgmt.com.crt
  delta: '0:00:00.665181'
  end: '2022-03-14 14:11:45.382152'
  failed_when_result: true
  msg: non-zero return code
  rc: 1
  start: '2022-03-14 14:11:44.716971'
  stderr: 'ipa: ERROR: an internal error has occurred'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
~~~

The error, in `/var/log/httpd/error_log` is the following:

~~~
[Mon Mar 14 14:11:38.025311 2022] [:warn] [pid 2141715:tid 140453475247872] [client 10.200.138.26:47808] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:38.034404 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47808] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: ping(): SUCCESS
[Mon Mar 14 14:11:38.036229 2022] [:warn] [pid 2141715:tid 140453466855168] [client 10.200.138.26:47808] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:38.153308 2022] [wsgi:error] [pid 2141711:tid 140453671933696] [remote 10.200.138.26:47808] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: host_find/1(None, version='2.240'): SUCCESS
[Mon Mar 14 14:11:39.916306 2022] [:warn] [pid 2144657:tid 140453013878528] [client 10.200.138.26:47814] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:39.924736 2022] [wsgi:error] [pid 2141712:tid 140453671933696] [remote 10.200.138.26:47814] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: ping(): SUCCESS
[Mon Mar 14 14:11:39.926495 2022] [:warn] [pid 2144657:tid 140453005485824] [client 10.200.138.26:47814] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:40.045998 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47814] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: host_find/1(None, version='2.240'): SUCCESS
[Mon Mar 14 14:11:41.790243 2022] [:warn] [pid 2141717:tid 140453643003648] [client 10.200.138.26:47820] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:41.798131 2022] [wsgi:error] [pid 2141711:tid 140453671933696] [remote 10.200.138.26:47820] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: ping(): SUCCESS
[Mon Mar 14 14:11:41.800353 2022] [:warn] [pid 2141717:tid 140453634610944] [client 10.200.138.26:47820] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:41.948938 2022] [wsgi:error] [pid 2141712:tid 140453671933696] [remote 10.200.138.26:47820] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: service_find/1(None, version='2.240'): SUCCESS
[Mon Mar 14 14:11:43.668634 2022] [:warn] [pid 2144657:tid 140452988700416] [client 10.200.138.26:47826] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:43.676893 2022] [wsgi:error] [pid 2141711:tid 140453671933696] [remote 10.200.138.26:47826] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: ping(): SUCCESS
[Mon Mar 14 14:11:43.678866 2022] [:warn] [pid 2144657:tid 140452980307712] [client 10.200.138.26:47826] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:43.694588 2022] [wsgi:error] [pid 2141712:tid 140453671933696] [remote 10.200.138.26:47826] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: service_add_host/1('HTTP/openmanage.mgmt.com', version='2.240', host=('gr-opmgprd01.mgmt.com',)): SUCCESS
[Mon Mar 14 14:11:45.310306 2022] [:warn] [pid 2141717:tid 140453592647424] [client 10.200.138.26:47832] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:45.318545 2022] [wsgi:error] [pid 2141713:tid 140453671933696] [remote 10.200.138.26:47832] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: ping(): SUCCESS
[Mon Mar 14 14:11:45.320855 2022] [:warn] [pid 2141717:tid 140453584254720] [client 10.200.138.26:47832] failed to set perms (3140) on file (/run/ipa/ccaches/service_certs@MGMT.COM-eadxj6)!, referer: https://gr-ipaprd01.mgmt.com/ipa/xml
[Mon Mar 14 14:11:45.329192 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832] ipa: ERROR: non-public: Error: Incorrect padding
[Mon Mar 14 14:11:45.329218 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832] Traceback (most recent call last):
[Mon Mar 14 14:11:45.329221 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipaserver/rpcserver.py", line 397, in wsgi_execute
[Mon Mar 14 14:11:45.329225 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     result = command(*args, **options)
[Mon Mar 14 14:11:45.329230 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 471, in __call__
[Mon Mar 14 14:11:45.329237 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     return self.__do_call(*args, **options)
[Mon Mar 14 14:11:45.329239 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 492, in __do_call
[Mon Mar 14 14:11:45.329242 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     params = self.convert(**params)
[Mon Mar 14 14:11:45.329244 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 693, in convert
[Mon Mar 14 14:11:45.329246 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     (k, self.params[k].convert(v)) for (k, v) in kw.items()
[Mon Mar 14 14:11:45.329249 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/frontend.py", line 693, in <genexpr>
[Mon Mar 14 14:11:45.329252 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     (k, self.params[k].convert(v)) for (k, v) in kw.items()
[Mon Mar 14 14:11:45.329256 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/parameters.py", line 853, in convert
[Mon Mar 14 14:11:45.329319 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     return convert(value)
[Mon Mar 14 14:11:45.329323 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/parameters.py", line 1521, in _convert_scalar
[Mon Mar 14 14:11:45.329327 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     value = self.__extract_der_from_input(value)
[Mon Mar 14 14:11:45.329329 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib/python3.6/site-packages/ipalib/parameters.py", line 1503, in __extract_der_from_input
[Mon Mar 14 14:11:45.329331 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     return base64.b64decode(value)
[Mon Mar 14 14:11:45.329333 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]   File "/usr/lib64/python3.6/base64.py", line 87, in b64decode
[Mon Mar 14 14:11:45.329344 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832]     return binascii.a2b_base64(s)
[Mon Mar 14 14:11:45.329349 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832] binascii.Error: Incorrect padding
[Mon Mar 14 14:11:45.329357 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832] 
[Mon Mar 14 14:11:45.329649 2022] [wsgi:error] [pid 2141714:tid 140453671933696] [remote 10.200.138.26:47832] ipa: INFO: [jsonserver_session] service_certs@MGMT.COM: cert_request/1('-----BEGIN CERTIFICATE REQUEST-----MIIFMDCCAxgCAQAwgbAxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhWaXJnaW5pYTESMBAGA1UEBwwJQXJsaW5ndG9uMRIwEAYDVQQKDAlCbHV2ZWN0b3IxHzAdBgNVBAsMFkRhdGEgQ2VudGVyIE9wZXJhdGlvbnMxJTAjBgNVBAMMHG9wZW5tYW5hZ2UubWdtdC5ibHV2ZWN0b3IuaW8xHjAcBgkqhkiG9w0BCQEWD2l0QGJsdXZlY3Rvci5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOWI3XaaWzz3Rb9uDTWobqmk2/IBWybQAzBGz/mIHFLdhwPYsr1L5RlI3ac2p0bdJ4W31lNmLWiHUJAPGyGx84IlHFADMA8inDZL8tjeXs7vhI04Opai6ZUthL8uImFcc9PvAu52SNglUMYdHVhZDJ7ckKItZNCsktBrIo43BkqBSEmFP1kD84WiXIzRSPg+GCamKBSP/ls2rJMM8UL1cyW9o+JTAjLbOx3kTu5qOnv3mQ6vXWWWLxBbHzv/oDMPSuEgMRk9LVCFJ5E+CPAXX4MYX3xeO2a0W9FSWRTeLBZq2C4pjhgEWkqd/il8vtJGtyGRO0yg6XU6rWbEEgkUXD3L1qPZhOJepB4BF1uh1sEUsS2eEEnc8ZLYrTKab+C2WNJ7mbmzrA2AXGqpFUdyojKl8WHJ23j4K4Gth+RVOlEgKxV9YfCbZog7VDWaxonyj540OFRubx8DNhMHWqhUezije+HbW+GmvZKl/POMLABbAkSTd4V9Ue3dg0+AZH549klvOaw1+Mp4JWxVtHo1uw1GgmewpdRAYH+Qq8xu6FXxTUTm/iCZ85AyPv2MyPjg6xFimN75vF7GdQwCu+77eGcZc664l52gDwO+XK/X0HxxBZ3ExStykirEOzWOSYoBdi8pLJva2+s8k1uLxm0PP6yxJ5kUQCjOPTVd3K2hZpjjAgMBAAGgOjA4BgkqhkiG9w0BCQ4xKzApMCcGA1UdEQQgMB6CHG9wZW5tYW5hZ2UubWdtdC5ibHV2ZWN0b3IuaW8wDQYJKoZIhvcNAQELBQADggIBAIE4K1fTMgBW3NRz5jsbai34F3QCvBOfZqcf+TzYq1FhljN+y5/XPd6WtsaJ0iOzdVRB2ywD2emHByEV7sTa6AowLLNW5ZNyzAJ/r+zJRt+jhpH5Tnpu6DnFn2vJmzpA+NVud4oiN+zzFpAmDHnYs0vVKrw2CgH1WhQvV5YVNyznkUEehIfmu8EvZd3W2klQBqXplbZeCk4nfXHayrfcZt1FhQLb0ElMg4CkBUVnt3/5Ev8M8jLE5zt6QQv0KO1if5fbt0K0jZY07vw6GaABLIf1zGNUu53YV1n3yUk+q36XAVaGKx5Puk2vmisI5RaSucclH4iEVx2FkhRKgD5xbWOZ4cyXFxi+RFp8bgA03d7hmSvn+Q1rYrb4mhHCSpF6NJCrYep2gnieTPfIvcQIqFfeMdBJTLxwgI6kYEZgvaZdB1re48CBPQ1WZ+HI2Mz0i0HX3hljGLnOL4PO5RuU+UNH+PGp9O51R1eVnEdX7CDcjJbdYYR4MmCi26hexxPZCPjmJUct056gc5yfplFGCX7/Vx6nrXfyF5HHoUZL3Oc5YkyR4FM4Or4ATaJGy7zO+tZvrPX68BlDWapPZK/u85N0nBd5G9I5FSGTE4DsharSHGPmeU3ML6jqYWrAQXyKFP8ERE02ndQwg9Uf4LTU3IL92/DCTpg57kYn8pZfsa3o-----END CERTIFICATE REQUEST-----\\n', principal='HTTP/openmanage.mgmt.com', add=True, version='2.240'): InternalError
~~~

I'm wondering if I'm missing a formatting step here that may be causing this issue?

**Comment by t-readyroc** [comment]
Get the following error  when attempting to validate that file:

~~~
[root@gr-ipaprd01 ~]# openssl req -in /tmp/openmanage.mgmt.com.csr -noout -text
unable to load X509 request
140446795388736:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: CERTIFICATE REQUEST
~~~

**Comment by t-readyroc** [comment]
Just popping back in to say that I just went to renew the certificate, and I'm still getting the same issue.  Ansible 2.13.7 & collection version 8.7.0 this time.

**Comment by anupamaloke** [comment]
@t-readyroc, thank you for sharing this. We will get this prioritized accordingly for future releases.
