### ISSUE TITLE
[BUG]: Issue with Importing SCP with RAID components in JSON format from a local path

### ISSUE THREAD

**Issue by TylerChecchia** [dell/dellemc-openmanage-ansible-modules#448]
### Bug Description

I've created a task which imports SCP with RAID components in a JSON format and this is the task:

```
 - name: Import SCP with RAID components in JSON format from a local path
   dellemc.openmanage.idrac_server_config_profile:
       idrac_ip: "{{vmware_ip}}"
       idrac_user: "{{idrac_username}}"
       idrac_password: "{{idrac_password}}"
       validate_certs: False
       share_name: "{{ playbook_dir }}/../files" 
       command: import
       scp_components: "RAID"
       scp_file: "idrac-scp-tcp-raid.json"
       shutdown_type: Graceful
       end_host_power_state: "On"
       job_wait: True 
```
however, once I run the task I get this error message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [hermes-srv2-9]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 107, in <module>
    _ansiballz_main()
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', init_globals=dict(_module_fqn='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 664, in <module>
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 655, in main
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Component or Module Name

dellemc.openmanage.idrac_server_config_profile

### Ansible Version

Ansible 2.13.1

### Python Version

Python 3.8.10

### iDRAC/OME/OME-M version

not specified 

### Operating System

not specified 

### Playbook Used

```
 - name: Import SCP with RAID components in JSON format from a local path
   dellemc.openmanage.idrac_server_config_profile:
       idrac_ip: "{{vmware_ip}}"
       idrac_user: "{{idrac_username}}"
       idrac_password: "{{idrac_password}}"
       validate_certs: False
       share_name: "{{ playbook_dir }}/../files" 
       command: import
       scp_components: "RAID"
       scp_file: "idrac-scp-tcp-raid.json"
       shutdown_type: Graceful
       end_host_power_state: "On"
       job_wait: True 
```

### Logs

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [hermes-srv2-9]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 107, in <module>
    _ansiballz_main()
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', init_globals=dict(_module_fqn='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 664, in <module>
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 655, in main
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps to Reproduce

Run playbook using command:
 
ansible-playbook -v playbooks/site.yml -i inventory/static_inventory.yml 

### Expected Behavior

should return a message saying success 

SCP operation job and progress details from the iDRAC.

Returned: success

### Actual Behavior

reruns the error 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [hermes-srv2-9]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 107, in <module>
    _ansiballz_main()
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/tyler/.ansible/tmp/ansible-tmp-1666346787.4116309-239954-248289563527048/AnsiballZ_idrac_server_config_profile.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', init_globals=dict(_module_fqn='ansible_collections.dellemc.openmanage.plugins.modules.idrac_server_config_profile', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 664, in <module>
  File "/tmp/ansible_idrac_server_config_profile_payload_tr7dlwni/ansible_idrac_server_config_profile_payload.zip/ansible_collections/dellemc/openmanage/plugins/modules/idrac_server_config_profile.py", line 655, in main
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by TylerChecchia** [comment]
Issue found, was using wrong IP address
