### ISSUE TITLE
dellemc_idrac_server_config_profile

### ISSUE THREAD

**Issue by alexskrc** [dell/dellemc-openmanage-ansible-modules#51]
hi there, I recently upgraded to the latest openmanage ansible modules and ansible 2.8.0. I am trying to configure an R630 and I am getting the error below while running the export. I get the same error if I try to configure the BIOS, so I am thinking the problem is not this specific task. Any insights will be greatly appreciated!

MSG:

MODULE FAILURE
See stdout/stderr for the exact error

MODULE_STDERR:

WARNING: yacc table file version is out of date
Traceback (most recent call last):
  File "/home/ansibleuser/.ansible/tmp/ansible-tmp-1559140602.51-269126448783444/AnsiballZ_dellemc_idrac_server_config_profile.py", line 114, in <module>
    _ansiballz_main()
  File "/home/ansibleuser/.ansible/tmp/ansible-tmp-1559140602.51-269126448783444/AnsiballZ_dellemc_idrac_server_config_profile.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansibleuser/.ansible/tmp/ansible-tmp-1559140602.51-269126448783444/AnsiballZ_dellemc_idrac_server_config_profile.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_dellemc_idrac_server_config_profile_payload_eUCJOp/__main__.py", line 304, in <module>
  File "/tmp/ansible_dellemc_idrac_server_config_profile_payload_eUCJOp/__main__.py", line 289, in main
  File "/tmp/ansible_dellemc_idrac_server_config_profile_payload_eUCJOp/ansible_dellemc_idrac_server_config_profile_payload.zip/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py", line 35, in __init__
KeyError: 'idrac_password'

**Comment by alexskrc** [comment]
Oooops sorry, I found issue #49 having the same kind of error. The resolution was:
"
- edit/usr/lib/python2.7/site-packages/ansible/module_utils/remote_management/dellemc/dellemc_idrac.py ; If running python3.x, then change the file path accordingly
- On line#35, change module_params['idrac_password'] to module_params['idrac_pwd']
save and close the file.
- Run the playbook again and verify that you do not run into the same KeyError: 'idrac_password'
"
